---
name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMPDIR: /tmp
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./test.sh
